import type { ContextOption } from '../model/types';

export const CONTEXTS: ContextOption[] = [
    // ─── IT / Work contexts ──────────────────────────────────────────────────
    {
        id: 'manager',
        label: 'Message to your manager',
        group: 'it-work',
        relationship: 'manager',
        channel: 'email/chat',
        styleId: 'executive',
        toneId: 'confident',
        formality: 'Consultative',
        structure: [
            'Lead with the ask, answer, or status in the first line (Bottom Line Up Front (BLUF)).',
            'Give the minimum context needed to act.',
            'State what you need from them and by when.',
        ],
        extraRules: [
            'Do not bury the ask under background or pleasantries.',
            'Do not over-apologize or hedge; state blockers as facts plus a proposed path.',
            'Keep it short — a manager should grasp it in one read.',
        ],
        exampleBefore:
            "Hi, hope you're well. So there's been a bunch of stuff going on with the release and I wanted to give some background before I get to my question...",
        exampleAfter:
            'Quick decision needed: I recommend we slip the release to Tuesday (DB migration needs one more day of testing). Risk of shipping Friday is an unverified rollback path. OK to move it?',
    },
    {
        id: 'senior-engineer',
        label: 'Ask a senior engineer for help',
        group: 'it-work',
        relationship: 'senior engineer',
        channel: 'chat/email',
        styleId: 'technical',
        toneId: 'respectful',
        formality: 'Consultative',
        structure: [
            "State the goal you're trying to achieve.",
            'Summarize what you already tried and what happened.',
            'Pinpoint the exact blocker or question.',
        ],
        extraRules: [
            'Show you respect their time: keep it tight, include a minimal reproducible example or specific code/error.',
            "Don't pretend to know something you don't; don't hand-wave the problem.",
            'Make it easy to answer with a yes/no or a pointer.',
        ],
        exampleBefore: "Hey, the auth thing isn't working, any ideas?",
        exampleAfter:
            'Trying to validate JWTs against our new issuer. I set the `iss` and `aud` claims per the runbook, but verification fails with `InvalidSignature`. I confirmed the key ID matches the JWKS. Am I missing a clock-skew or kid-rotation step?',
    },
    {
        id: 'junior-dev-feedback',
        label: 'Give a junior developer feedback',
        group: 'it-work',
        relationship: 'junior developer',
        channel: 'chat/review/1:1',
        styleId: 'instructional',
        toneId: 'supportive',
        formality: 'Consultative',
        structure: [
            'Situation–Behavior–Impact (SBI): name the specific situation, the observed behavior, and its impact.',
            'Give one concrete, actionable next step.',
            'End with encouragement and an offer to help.',
        ],
        extraRules: [
            'Critique the work, not the person; use "I noticed…", never "you always…".',
            'No condescension and no jargon dumps; define terms.',
            'Give feedback privately for anything corrective.',
        ],
        exampleBefore: 'Your code is sloppy, fix it.',
        exampleAfter:
            "On the PR yesterday (situation), the error paths weren't handled (behavior), so failures would surface as a 500 to users (impact). Could you add explicit handling there? Happy to pair on it — you're picking this up fast.",
    },
    {
        id: 'code-review-comment',
        label: 'Code-review comment',
        group: 'it-work',
        relationship: 'code author',
        channel: 'pull-request review',
        styleId: 'technical',
        toneId: 'collaborative',
        formality: 'Consultative',
        structure: [
            'Observation: state what you see in the code.',
            'Why: explain the concern or risk.',
            'Suggestion: frame the fix as a request or option ("What do you think?").',
        ],
        extraRules: [
            'Critique the code, not the person; avoid "you" attacks and commands.',
            'Offload pure style nits to linters/formatters; focus on substance.',
            'Distinguish blocking issues from optional nits explicitly.',
        ],
        exampleBefore: 'This method is very inefficient. Why did you do this?',
        exampleAfter:
            'This loop re-queries inside the iteration (observation), which will be an N+1 on large inputs (why). Could we batch the lookup before the loop? What do you think?',
    },
    {
        id: 'pr-description',
        label: 'Pull Request (PR) description',
        group: 'it-work',
        relationship: 'reviewers',
        channel: 'pull-request',
        styleId: 'technical',
        toneId: 'neutral',
        formality: 'Consultative',
        structure: [
            'What changed (a concise summary).',
            'Why it changed (the motivation/issue link).',
            'How it was tested (test plan, screenshots for UI).',
        ],
        extraRules: [
            'Explain what and why, not how — the "how" is the diff.',
            'Keep the change small and focused; link the issue.',
            'Expand abbreviations as "Full Name (ABBR)" (this is a Pull Request (PR)).',
        ],
        exampleBefore: 'Fixed the bug.',
        exampleAfter:
            '## What — Validate the `iss` claim on inbound tokens. ## Why — Closes #482; tokens from the old issuer were being accepted. ## Testing — Added unit tests for valid/invalid issuers; verified staging rejects legacy tokens.',
    },
    {
        id: 'customer-reply',
        label: 'Reply to a customer',
        group: 'it-work',
        relationship: 'customer',
        channel: 'support/email',
        styleId: 'customer-facing',
        toneId: 'reassuring',
        formality: 'Consultative',
        structure: [
            "Acknowledge the issue and the customer's frustration (empathy first).",
            'State the fix or the concrete next step.',
            'Set an expectation: what happens next and by when.',
        ],
        extraRules: [
            'No blame, no internal jargon, no defensiveness.',
            'Take responsibility on behalf of the company.',
            'Respond quickly (within 24–48 hours); avoid "sorry for any inconvenience".',
        ],
        exampleBefore: "That's not a bug, you configured it wrong.",
        exampleAfter:
            "Thanks for flagging this — I'm sorry it's been disrupting your workflow. The setting wasn't applying as expected; we've corrected it and it should work for you now. I'll keep your ticket open until you confirm. Anything else I can help with?",
    },
    {
        id: 'stakeholder-update',
        label: 'Update a stakeholder',
        group: 'it-work',
        relationship: 'stakeholder',
        channel: 'email/report',
        styleId: 'executive',
        toneId: 'diplomatic',
        formality: 'Consultative–Formal',
        structure: [
            'Lead with the outcome and the "so what" (impact on goals).',
            'Quantify status, risk, and timeline.',
            'State any decision or support you need.',
        ],
        extraRules: [
            'Translate technical detail into business impact; no jargon dumps.',
            'Be candid about risk while staying constructive.',
            'One screen or less.',
        ],
        exampleBefore: 'We refactored the data layer and fixed some queries and stuff.',
        exampleAfter:
            "On track for the Q3 launch. This sprint cut page-load time 40% (the top customer complaint). One risk: the analytics migration is a week behind — I'd like to pull in one engineer to hold the date. OK to reallocate?",
    },
    {
        id: 'slack-teams',
        label: 'Slack / Microsoft Teams quick message',
        group: 'it-work',
        relationship: 'team',
        channel: 'Slack/Teams',
        styleId: 'chat-message',
        toneId: 'friendly',
        formality: 'Casual',
        structure: [
            'Lead with the ask in the first line.',
            'Add minimal context on the same message.',
            'Move detail or back-and-forth into a thread.',
        ],
        extraRules: [
            "One idea per message; don't fragment a thought across many messages.",
            'Respect async norms (time zones, do-not-disturb); use schedule-send when off-hours.',
            'Use emoji reactions instead of "got it" noise.',
        ],
        exampleBefore: 'Hey. You there? I have a question.',
        exampleAfter:
            'Could you review the budget draft by Friday? Mainly need eyes on the Q3 column — link in thread. No rush before then 🙏',
    },
    {
        id: 'standup',
        label: 'Stand-up / status update',
        group: 'it-work',
        relationship: 'team/manager',
        channel: 'standup/status',
        styleId: 'neutral',
        toneId: 'neutral',
        formality: 'Consultative',
        structure: [
            'Done: what you completed (outcomes, not activity).',
            "Doing: what you're working on next.",
            "Blockers: what's stopping you and what you need.",
        ],
        extraRules: [
            'Report outcomes, not a list of activity.',
            'Name a specific owner/help needed for each blocker.',
            'Keep it to a few lines.',
        ],
        exampleBefore: 'I worked on the API yesterday and did some stuff with the database and meetings.',
        exampleAfter:
            'Done: token issuer validation shipped to staging. Doing: wiring the same check into the gateway. Blocker: need DBA review on the index migration — @Sam, can you look today?',
    },
    {
        id: 'recruiter-interview',
        label: 'Reply to a recruiter or interviewer',
        group: 'it-work',
        relationship: 'recruiter/interviewer',
        channel: 'email/message',
        styleId: 'professional',
        toneId: 'enthusiastic',
        formality: 'Consultative',
        structure: [
            'Warm, brief opener that signals genuine interest.',
            'Specific point of fit (skills/experience ↔ the role); use Situation–Task–Action–Result (STAR) for interview answers.',
            'Clear next step (availability, attached materials, a question).',
        ],
        extraRules: [
            'Be specific about fit; avoid both desperation and arrogance.',
            'Never badmouth a current or past employer.',
            'Keep enthusiasm genuine, not gushing.',
        ],
        exampleBefore: "I'm interested in the job. I think I'd be good at it.",
        exampleAfter:
            "Thanks for reaching out — the platform-reliability focus is exactly what I want to do next. I led an on-call overhaul that cut pages 60% in two quarters, which maps closely to your reliability goals. I'm free Tue/Thu afternoon for a call — what works for you?",
    },
    {
        id: 'hr',
        label: 'Message to Human Resources (HR)',
        group: 'it-work',
        relationship: 'HR',
        channel: 'email',
        styleId: 'professional',
        toneId: 'neutral',
        formality: 'Consultative–Formal',
        structure: [
            'State the matter and the specific request clearly.',
            'Provide facts, dates, and any reference numbers.',
            "State the outcome you're seeking and a reasonable timeline.",
        ],
        extraRules: [
            'Keep it factual and documented; avoid emotional escalation.',
            'Be precise and unambiguous; this may become a record.',
            'Expand abbreviations (this is Human Resources (HR)).',
        ],
        exampleBefore: 'This whole situation is ridiculous and someone needs to do something now!!',
        exampleAfter:
            "I'm writing to formally request clarification on the parental-leave policy (ref: handbook §6.2). I expect to take leave starting 1 September and need to confirm the notice period and pay schedule. Could you advise on next steps by the end of the week?",
    },
    {
        id: 'linkedin-post',
        label: 'LinkedIn post',
        group: 'it-work',
        relationship: 'professional network',
        channel: 'LinkedIn',
        styleId: 'social-media',
        toneId: 'confident',
        formality: 'Consultative',
        structure: [
            'Hook in the first one or two lines (before the ~210-character "see more" cutoff).',
            'Deliver genuine insight or a concrete story.',
            'End with an authentic engagement prompt or takeaway.',
        ],
        extraRules: [
            'No engagement bait; no AI-generic phrasing ("in today\'s fast-paced world").',
            'Use ≤5 hashtags; front-load the value.',
            'Include a specific number, name, or example.',
        ],
        exampleBefore:
            "I'm excited to share that I learned something interesting recently about engineering and wanted to post about it for my network!",
        exampleAfter:
            "We deleted 40% of our test suite last quarter — and reliability went up. Counterintuitive, but a wall of brittle tests was hiding the failures that mattered. Three things we did instead: [1] … [2] … [3] … What's your take on test-suite bloat?",
    },
    {
        id: 'x-threads-post',
        label: 'X / Threads post',
        group: 'it-work',
        relationship: 'public',
        channel: 'X/Threads',
        styleId: 'social-media',
        toneId: 'casual',
        formality: 'Casual',
        structure: [
            'Open with a punchy hook in the first line.',
            'One core idea per post; use a thread for depth.',
            'Land a clear point or question.',
        ],
        extraRules: [
            "Keep it brief; don't force virality.",
            'Threads can be slightly more casual than X.',
            'Avoid hashtag stuffing.',
        ],
        exampleBefore:
            'Here is a long single post with many different ideas crammed together about testing and CI and code review and...',
        exampleAfter:
            "Hot take: most CI is slow because nobody owns it. We made one person the 'build steward' for a sprint. Result: 11min → 4min. Thread on what they changed 👇",
    },
    {
        id: 'forum-stackoverflow',
        label: 'Forum / Stack Overflow / open-source issue',
        group: 'it-work',
        relationship: 'community',
        channel: 'forum/Stack Overflow/issue tracker',
        styleId: 'community',
        toneId: 'respectful',
        formality: 'Consultative',
        structure: [
            "State the goal (what you're trying to achieve).",
            'Show what you tried and the exact result/error.',
            'Provide a minimal reproducible example and environment details.',
        ],
        extraRules: [
            "Search first and say so; follow the community's norms.",
            "Stay courteous — you're asking for help, not demanding results.",
            'Post the resolution once solved.',
        ],
        exampleBefore: "My code doesn't work, please help asap.",
        exampleAfter:
            "Goal: parse ISO-8601 dates with a trailing `Z` in Python 3.12. Tried `datetime.fromisoformat(s)` (docs say it's supported) but it raises `ValueError` on `2026-06-21Z`. Minimal repro and full traceback below. Env: Python 3.12.2, Linux. What's the correct approach?",
    },
    {
        id: 'jira-confluence',
        label: 'Jira ticket / Confluence page',
        group: 'it-work',
        relationship: 'team',
        channel: 'Jira/Confluence',
        styleId: 'documentation',
        toneId: 'neutral',
        formality: 'Consultative',
        structure: [
            'Actionable, specific title (Jira) or descriptive heading (Confluence).',
            'Context and acceptance criteria (Jira) or scannable headings (Confluence).',
            'Reproducible detail / links / owner.',
        ],
        extraRules: [
            'Make titles actionable and unambiguous; no "fix stuff".',
            'Keep Confluence pages findable and current; assign an owner.',
            'Include reproduction steps and environment for bugs.',
        ],
        exampleBefore: 'Ticket: login broken',
        exampleAfter:
            'Ticket: Reject login when token issuer is the legacy URL. Context: legacy-issuer tokens are still accepted (#482). Acceptance: gateway returns 401 for `iss=old.example.com`; unit + staging tests pass. Steps to reproduce in description.',
    },
    // ─── Everyday-life contexts ───────────────────────────────────────────────
    {
        id: 'friend',
        label: 'Message a friend',
        group: 'everyday',
        relationship: 'friend',
        channel: 'chat/SMS',
        styleId: 'casual',
        toneId: 'warm',
        formality: 'Casual–Intimate',
        structure: [
            'Open naturally — no formal salutation.',
            'Get to the point conversationally.',
            'Keep it warm and personal.',
        ],
        extraRules: ["Don't over-formalize; it reads as distance.", 'Humor and emoji are welcome.'],
        exampleBefore: 'Dear friend, I am writing to inquire whether you would be available this coming weekend.',
        exampleAfter: 'Hey! You around this weekend? Was thinking we could grab food Saturday — been ages 😄',
    },
    {
        id: 'family',
        label: 'Family / parent note',
        group: 'everyday',
        relationship: 'family',
        channel: 'chat/call note',
        styleId: 'casual',
        toneId: 'warm',
        formality: 'Casual–Intimate',
        structure: ['Warm, personal opener.', 'The news or the ask.', 'A caring close.'],
        extraRules: ['Avoid a cold, transactional tone.', "Don't assume context they may not have."],
        exampleBefore: 'Confirming dinner attendance for Sunday. Arrival 6pm.',
        exampleAfter:
            "Hi Mum — yes, we'll be there Sunday around 6! Can't wait to see you both. Want me to bring dessert? Love you x",
    },
    {
        id: 'neighbor',
        label: 'Neighbor request',
        group: 'everyday',
        relationship: 'neighbor',
        channel: 'note/message',
        styleId: 'friendly',
        toneId: 'friendly',
        formality: 'Polite-casual',
        structure: [
            'Friendly greeting and who you are (if needed).',
            'The request, with relevant specifics.',
            'Thanks and an easy way to respond.',
        ],
        extraRules: [
            'Not too formal (standoffish) or too familiar (presumptuous).',
            'Keep it considerate of their time and space.',
        ],
        exampleBefore: 'Your dog barks. Please make it stop.',
        exampleAfter:
            "Hi! I'm Alex from number 14. I wanted to gently flag that the dog's been barking a fair bit in the early mornings lately — totally understand it happens. Would a quick chat about it help? Thanks so much!",
    },
    {
        id: 'landlord',
        label: 'Reply to a landlord (repair / rent / dispute)',
        group: 'everyday',
        relationship: 'landlord',
        channel: 'email/message',
        styleId: 'semi-formal',
        toneId: 'assertive',
        formality: 'Consultative',
        structure: [
            'State the issue with date and specifics.',
            'State the concrete request.',
            'Give a by-when and ask them to confirm.',
        ],
        extraRules: [
            'Keep a documentable record; be calm and factual, never hostile.',
            'Reference dates, amounts, and prior messages.',
            'State the boundary or deadline clearly.',
        ],
        exampleBefore: "the heating still doesn't work, this is unacceptable, fix it",
        exampleAfter:
            "Hi — following up on the heating, which has been out since 12 June (reported then and on the 15th). It's now affecting daily use. Please arrange a repair by Friday 26 June, or let me know the plan and timeline. Could you confirm by tomorrow? Thanks.",
    },
    {
        id: 'service-provider',
        label: 'Service provider (refund / complaint / booking)',
        group: 'everyday',
        relationship: 'service provider',
        channel: 'email/chat',
        styleId: 'professional',
        toneId: 'assertive',
        formality: 'Consultative',
        structure: [
            'State the order/account reference and the issue.',
            'State the specific resolution you want.',
            'Give a reasonable deadline and ask for confirmation.',
        ],
        extraRules: [
            'Be specific and firm without hostility — escalation hurts your case.',
            'Include reference numbers, dates, and amounts.',
            'Keep a calm, documented record.',
        ],
        exampleBefore: 'Your service is terrible and I want my money back now!!!',
        exampleAfter:
            "Re: order #88231 (placed 10 June). The item arrived damaged and the replacement hasn't shipped after two weeks. I'd like a full refund of £49.99 to my original payment method. Please confirm you'll process this within 5 business days.",
    },
    {
        id: 'government-agency',
        label: 'Government agency letter',
        group: 'everyday',
        relationship: 'government agency',
        channel: 'formal letter/email',
        styleId: 'formal',
        toneId: 'neutral',
        formality: 'Formal',
        structure: [
            'Reference line: case/reference number and subject.',
            'State the matter factually with relevant dates and documents.',
            'State the specific action requested and any deadline.',
        ],
        extraRules: [
            'Include reference numbers; attach/cite supporting documents.',
            'No slang, no emotional appeals.',
            'Keep it precise, complete, and documented.',
        ],
        exampleBefore: "I've been waiting forever and I'm really upset about my application!",
        exampleAfter:
            'Re: Application ref. ABC-2026-04417. I am writing regarding my application submitted on 3 April 2026, which remains pending. Please advise the current status and expected decision date. I have attached the acknowledgement receipt for reference. Thank you for your assistance.',
    },
    {
        id: 'police',
        label: 'Police statement / report',
        group: 'everyday',
        relationship: 'police',
        channel: 'statement/report',
        styleId: 'formal',
        toneId: 'respectful',
        formality: 'Formal',
        structure: [
            'State the facts in chronological order with dates, times, and locations.',
            'Describe only what you directly observed.',
            'Provide your contact and reference details.',
        ],
        extraRules: [
            'Facts only — no speculation or interpretation.',
            'Do not volunteer excess or unrelated detail.',
            'Keep it calm, brief, and factual.',
        ],
        exampleBefore: "I think maybe the guy who's always hanging around probably did it, he seems dodgy.",
        exampleAfter:
            'On 20 June 2026 at approximately 21:30, I observed an individual remove a bicycle from the rack outside 14 High Street. I did not see their face clearly. The bicycle was black, ref. frame number on file. I am available to provide further details if needed.',
    },
    {
        id: 'community-post',
        label: 'Community / Reddit post',
        group: 'everyday',
        relationship: 'online community',
        channel: 'Reddit/forum/neighborhood board',
        styleId: 'community',
        toneId: 'casual',
        formality: 'Casual',
        structure: [
            'A clear, honest title/opener.',
            'Context and the specific point or question.',
            "Respect for the community's norms.",
        ],
        extraRules: [
            'Follow the subreddit/community rules; no marketing speak.',
            'Be authentic and norm-aware; avoid performative outrage.',
            'Give enough context for a useful reply.',
        ],
        exampleBefore: "Check out my product, it's amazing, link below!",
        exampleAfter:
            "[Question] First time setting up a home network for a flat — any gotchas? I've got a basic router and ~6 devices. Mostly worried about dead spots in the back room. What worked for people with a similar setup? (Mods — let me know if this belongs in the weekly thread.)",
    },
    {
        id: 'article',
        label: 'Write an article / blog post',
        group: 'everyday',
        relationship: 'public readers',
        channel: 'blog/publication',
        styleId: 'journalistic',
        toneId: 'confident',
        formality: 'Casual–Consultative',
        structure: [
            'Hook: open with a specific moment, claim, or question.',
            'Body: develop the point with concrete detail and a real point of view.',
            'Takeaway: land one clear conclusion.',
        ],
        extraRules: [
            "Don't bury the lead; front-load the value.",
            'Use specifics (names, dates, numbers); avoid AI-generic phrasing.',
            'Keep one through-line.',
        ],
        exampleBefore:
            'In this article, we will explore some thoughts about the topic of software reliability in modern systems.',
        exampleAfter:
            "At 3 a.m. the pager went off for the fourth night running — and that's when we realized our alerting was the actual problem. Here's how cutting our alerts by half made us more reliable, not less.",
    },
    // ─── Edge-case / difficult-message contexts ───────────────────────────────
    {
        id: 'disagreement',
        label: 'Express disagreement',
        group: 'edge-case',
        relationship: 'colleague/peer',
        channel: 'any',
        styleId: 'persuasive',
        toneId: 'diplomatic',
        formality: 'Consultative',
        structure: [
            'Acknowledge the other position fairly.',
            'State your concern with reasons (not feelings).',
            'Offer a concrete alternative or a path that combines both.',
        ],
        extraRules: [
            'Frame it as "us vs. the problem", not "me vs. you".',
            'Use reasons and evidence; avoid "you always/never".',
            'If the thread exceeds ~3 round-trips, propose a call.',
        ],
        exampleBefore: "Your plan is wrong and won't scale, we should do mine.",
        exampleAfter:
            "I see why the queue-per-tenant approach is appealing — it's simple to reason about. My concern is cost at 10k tenants. Could we get the isolation you want with a shared queue plus tenant tags? Happy to prototype both and compare.",
    },
    {
        id: 'sensitive-topic',
        label: 'Raise a sensitive topic',
        group: 'edge-case',
        relationship: 'any',
        channel: 'private/1:1',
        styleId: 'semi-formal',
        toneId: 'empathetic',
        formality: 'Consultative',
        structure: [
            'Lead with care and the intent behind raising it.',
            'State the specific point clearly, without euphemism that obscures.',
            'Invite a two-way conversation.',
        ],
        extraRules: [
            'Use a private channel; never raise it publicly.',
            'Lead with care; avoid vague euphemism that hides the real issue.',
            'Be respectful and give the person room to respond.',
        ],
        exampleBefore: "We need to talk about your performance, it's been bad.",
        exampleAfter:
            "I wanted to raise something one-on-one because I care about how things are going for you. I've noticed the last two deadlines slipped, and I want to understand what's getting in the way and how I can help. Can we talk this week?",
    },
    {
        id: 'receiving-criticism',
        label: 'Respond to criticism you received',
        group: 'edge-case',
        relationship: 'any',
        channel: 'any',
        styleId: 'professional',
        toneId: 'respectful',
        formality: 'Consultative',
        structure: [
            'Thank the person for the feedback.',
            'Clarify or ask a question to fully understand it.',
            'Separate yourself from the work; state your next step.',
        ],
        extraRules: [
            "Stay open and non-defensive; don't justify reflexively.",
            'Treat feedback on the work as about the work, not your worth.',
            "Confirm what you'll do differently.",
        ],
        exampleBefore: "That's not fair, you don't understand, I did my best!",
        exampleAfter:
            "Thanks for the honest feedback — I'd rather hear it. To make sure I understand: is the main issue the missing error handling, or the structure overall? I'll fix the error paths today and follow up on the rest.",
    },
    {
        id: 'urgent',
        label: 'Urgent message',
        group: 'edge-case',
        relationship: 'any',
        channel: 'any',
        styleId: 'public-announcement',
        toneId: 'serious',
        formality: 'Consultative',
        structure: [
            'Lead with the severity and the single most important ask.',
            "State the facts: what's happening, scope, and impact.",
            'State exactly what you need and by when.',
        ],
        extraRules: [
            'Put severity and the ask first; facts before detail.',
            'Use any agreed alert words/severity labels.',
            'Stay calm and directive; no speculation.',
        ],
        exampleBefore: 'Hey when you get a chance could you maybe look at prod? Something seems off I think.',
        exampleAfter:
            "URGENT (SEV-2): Checkout is failing for ~30% of users since 14:05 UTC. Need an on-call engineer to look now. I've paged @oncall; can you confirm you're on it? Details in #incident-checkout.",
    },
    {
        id: 'public-announcement',
        label: 'Public announcement',
        group: 'edge-case',
        relationship: 'broad audience',
        channel: 'status page/email/broadcast',
        styleId: 'public-announcement',
        toneId: 'authoritative',
        formality: 'Formal–Consultative',
        structure: [
            'Lead with what happened (or is changing) and its impact.',
            'State the next step and what the reader should do.',
            'Point to a single source of truth for updates.',
        ],
        extraRules: [
            'Give timestamps and scope (who is affected).',
            "No jargon; no speculation about cause before it's confirmed.",
            'One authoritative source of truth.',
        ],
        exampleBefore: "Hey all, site's a bit weird right now, we're on it, more later!",
        exampleAfter:
            'Service disruption (09:14 UTC): EU customers cannot log in. Cause identified; fix deploying now. No action needed on your side. Next update by 10:00 UTC at status.example.com.',
    },
];
