import type { ModelDef } from '../model/types';

export const MODELS: ModelDef[] = [
    {
        id: 'nano-banana-pro',
        label: 'Nano Banana Pro',
        slug: 'nano-banana-pro',
        modality: ['image-gen', 'image-edit'],
        defaults: { resolution: 'up to 4K; preserve source aspect ratio', aspectRatio: 'same as source (no crop)' },
    },
    {
        id: 'qwen-image',
        label: 'Qwen Image',
        slug: 'qwen-image',
        modality: ['image-gen'],
        defaults: { cfg: 'true_cfg_scale ~4.0; guidance_scale 1.0', steps: '40–50', resolution: 'up to 2560×2560' },
    },
    {
        id: 'qwen-image-edit-2511',
        label: 'Qwen Image Edit 2511',
        slug: 'qwen-image-edit-2511',
        modality: ['image-edit'],
        defaults: { cfg: 'true_cfg_scale 4.0; guidance_scale 1.0', steps: '40–50', resolution: 'up to 2560×2560' },
    },
    {
        id: 'flux-2',
        label: 'FLUX.2',
        slug: 'flux-2',
        modality: ['image-gen', 'image-edit'],
        defaults: { cfg: 'guidance_scale ~4', steps: '28–50', resolution: '1024×1024 and up' },
    },
    {
        id: 'flux-2-klein',
        label: 'FLUX.2 Klein',
        slug: 'flux-2-klein',
        modality: ['image-gen', 'image-edit'],
        defaults: { cfg: 'guidance_scale 1.0', steps: '4', resolution: '1024×1024' },
    },
    {
        id: 'gpt-image',
        label: 'GPT Image',
        slug: 'gpt-image',
        modality: ['image-gen', 'image-edit'],
        defaults: {
            resolution: 'set output quality to High; same aspect ratio as source',
            aspectRatio: 'match the source image',
        },
    },
    {
        id: 'stable-diffusion',
        label: 'Stable Diffusion',
        slug: 'stable-diffusion',
        modality: ['image-gen', 'image-edit'],
        defaults: {
            cfg: '6–8 (SDXL) / 4–7 (SD 3.5)',
            steps: '25–40',
            sampler: 'DPM++ 2M Karras',
            resolution: '1024×1024 (SDXL)',
            denoisingStrength: '0.4–0.55 for portraits',
        },
    },
    {
        id: 'joyai',
        label: 'JoyAI',
        slug: 'joyai',
        modality: ['image-edit'],
        defaults: { cfg: 'guidance_scale 4.0', steps: '30–50', resolution: 'basesize 1024' },
    },
    {
        id: 'veo',
        label: 'Veo',
        slug: 'veo',
        modality: ['video'],
        defaults: { duration: '4 / 6 / 8s', resolution: '720p / 1080p / 4K', fps: '24', aspectRatio: '16:9 or 9:16' },
    },
    {
        id: 'kling',
        label: 'Kling',
        slug: 'kling',
        modality: ['video'],
        defaults: { duration: '5 / 10s', resolution: '4K @ 60fps', aspectRatio: '16:9 / 9:16 / 1:1' },
    },
    {
        id: 'runway',
        label: 'Runway',
        slug: 'runway',
        modality: ['video'],
        defaults: { duration: '5 / 10s', resolution: '720p+', aspectRatio: '16:9 / 9:16' },
    },
    {
        id: 'seedance',
        label: 'Seedance',
        slug: 'seedance',
        modality: ['video'],
        defaults: { duration: '4–15s', resolution: '480p / 720p / 1080p' },
    },
    {
        id: 'hailuo',
        label: 'Hailuo',
        slug: 'hailuo',
        modality: ['video'],
        defaults: { duration: '6s default; up to 10s', resolution: '720p / 1080p', aspectRatio: '16:9' },
    },
    {
        id: 'luma',
        label: 'Luma',
        slug: 'luma',
        modality: ['video'],
        defaults: { duration: '5–10s', resolution: 'up to 1080p', aspectRatio: '16:9 / 9:16 / 3:4 / 1:1 / 4:3 / 21:9' },
    },
    {
        id: 'pika',
        label: 'Pika',
        slug: 'pika',
        modality: ['video'],
        defaults: {
            duration: '3–5s default; up to ~25s via Pikaframes',
            resolution: 'up to 1080p',
            aspectRatio: '9:16 / 16:9 / 1:1',
        },
    },
    {
        id: 'wan-local',
        label: 'Wan (local)',
        slug: 'wan-local',
        modality: ['video'],
        defaults: { duration: '~5s', resolution: '480p / 720p', fps: '16', aspectRatio: '16:9 / 9:16 / 1:1' },
    },
    {
        id: 'wan-api',
        label: 'Wan (API)',
        slug: 'wan-api',
        modality: ['video'],
        defaults: { duration: '~10–15s', resolution: 'up to 1080p', aspectRatio: '16:9 / 9:16 / 1:1 / 4:3 / 3:4' },
    },
    {
        id: 'hunyuan',
        label: 'HunyuanVideo',
        slug: 'hunyuan-video',
        modality: ['video'],
        defaults: { cfg: '6', steps: '50', duration: '~5s', resolution: '480p / 720p', fps: '24', aspectRatio: '16:9' },
    },
    {
        id: 'ltx',
        label: 'LTX',
        slug: 'ltx',
        modality: ['video'],
        defaults: { cfg: 'guidance ~4', duration: '6 / 8 / 10s', resolution: 'up to 4K', fps: '24 / 25 / 48 / 50' },
    },
    {
        id: 'cogvideox',
        label: 'CogVideoX',
        slug: 'cogvideox',
        modality: ['video'],
        defaults: { duration: '6–10s', resolution: '720×480', fps: '8' },
    },
    {
        id: 'mochi',
        label: 'Mochi',
        slug: 'mochi',
        modality: ['video'],
        defaults: { duration: '~5s', resolution: '480p' },
    },
];
