import type { RuleOption } from '../model/types';

export const STYLES: RuleOption[] = [
    {
        id: 'formal',
        label: 'Formal',
        definition: 'Impersonal, rule-correct prose with no contractions or slang, for high-stakes or ceremonial text.',
        rules: [
            'Use no contractions (write "do not", not "don\'t"; "we will", not "we\'ll").',
            'Use no slang, idioms, phrasal-verb casualness ("get done", "sort out"), or filler ("stuff", "things", "a lot").',
            'Prefer precise, often Latinate vocabulary ("unable", "regret", "request" over "can\'t", "sorry", "want").',
            'Allow longer, fully-formed sentences with subordinate clauses; never use fragments.',
            'Use third person or impersonal constructions where natural; passive voice is acceptable.',
            'Spell out every abbreviation on first use as "Full Name (ABBR)".',
            'Use no emoji, exclamation marks, or rhetorical questions.',
        ],
        do: [
            'State requests and conclusions explicitly and completely.',
            'Maintain a consistent, neutral register from greeting to close.',
        ],
        dont: [
            'Use exclamation marks, emoji, "!", or casual interjections ("heads up", "btw").',
            'Use second-person breeziness or jokes.',
        ],
        exampleBefore: "We can't get this done by Friday, sorry!",
        exampleAfter: 'We will be unable to complete this by Friday; we regret the delay.',
    },
    {
        id: 'semi-formal',
        label: 'Semi-formal',
        definition:
            'Polished but human prose with light contractions, the workhorse register for business email and client documents.',
        rules: [
            'Allow light, common contractions ("we\'ll", "you\'re"); avoid heavy casual ones ("gonna", "wanna").',
            'Use standard, professional vocabulary; no slang and no legalese.',
            'Keep sentences medium length (roughly 12–22 words); vary slightly to avoid monotony.',
            'Use second person ("you") and first person ("we") naturally; active voice preferred.',
            'Keep at most one exclamation mark per message; no emoji in external/client text.',
            'Greeting + body + courteous close where the channel expects it.',
        ],
        do: ['Open with a brief courteous line, then get to the point.', 'Keep one clear ask or purpose per message.'],
        dont: ['Use slang, emoji-laden lists, or fragments.', 'Drift into stiff Latinate phrasing that reads as cold.'],
        exampleBefore: 'yo can u send the file whenever, no rush lol',
        exampleAfter:
            "Hi — could you send the file when you get a chance? No urgency, but I'd appreciate it this week.",
    },
    {
        id: 'neutral',
        label: 'Neutral',
        definition: 'Objective, fact-first prose with no emotional coloring, for reference docs and status reporting.',
        rules: [
            'State facts plainly using denotative vocabulary; carry no opinion or persuasion.',
            'Keep sentence length even and predictable; avoid rhetorical flourish.',
            'Use no intensifiers ("very", "extremely", "amazing") and no value judgements.',
            'Use active voice with concrete subjects; present tense for current state.',
            'Quantify where possible (numbers, dates, IDs) instead of qualitative description.',
            'Use no emoji, exclamation marks, or rhetorical questions.',
        ],
        do: [
            'Lead each statement with the fact, then any supporting detail.',
            'Attribute claims to a source when relevant.',
        ],
        dont: ['Editorialize, praise, or blame.', 'Use marketing or persuasive language.'],
        exampleBefore: 'The migration went amazingly well and everyone was thrilled!',
        exampleAfter: 'The migration completed at 02:14 UTC with no errors; all 14 services passed health checks.',
    },
    {
        id: 'professional',
        label: 'Professional',
        definition: 'Competent, courteous, outcome-focused prose — the default workplace register.',
        rules: [
            'Use active voice and concrete verbs; lead with the outcome or ask.',
            'Use domain terms precisely and expand each abbreviation on first use as "Full Name (ABBR)".',
            'Keep sentences clear and medium length; one idea per sentence.',
            'Allow light contractions; keep tone courteous but not effusive.',
            'Use no slang, no emoji in formal threads, and no passive-aggression.',
            'Close with a clear next step or owner when action is needed.',
        ],
        do: [
            'Make the request, decision, or recommendation explicit and early.',
            'Name owners and deadlines for any action item.',
        ],
        dont: ['Bury the ask under context or pleasantries.', 'Use jargon the reader will not know without expansion.'],
        exampleBefore: "Just wanted to maybe possibly check if you'd had a chance to look at the thing?",
        exampleAfter:
            'Could you review the deployment plan by Thursday? I need your sign-off before we schedule the release.',
    },
    {
        id: 'business',
        label: 'Business',
        definition:
            'Professional prose that is transactional and action-oriented, framed around cost, timeline, and return.',
        rules: [
            'Frame content around concrete outcomes: scope, cost, timeline, and return on investment.',
            'Use concrete nouns and quantified figures (dates, amounts, percentages).',
            'Lead with the proposal or decision, then supporting numbers.',
            'Keep sentences direct and economical; no narrative digression.',
            'Use active voice; assign owners to deliverables.',
            'Expand all abbreviations as "Full Name (ABBR)" on first use.',
        ],
        do: ['Tie every point to a business outcome or a number.', 'State the ask and the by-when up front.'],
        dont: ['Use creative storytelling or emotional appeals.', 'Leave figures vague ("soon", "a lot", "cheaper").'],
        exampleBefore: 'We think doing this could really help us out a bunch over time.',
        exampleAfter:
            'Adopting the managed queue cuts ops effort by roughly 8 hours/week and pays back the $1,200/mo cost within two quarters.',
    },
    {
        id: 'friendly',
        label: 'Friendly',
        definition: 'Warm, approachable, personal prose that uses "you" and "we" and everyday words.',
        rules: [
            'Use contractions and everyday vocabulary; avoid Latinate or legalese.',
            'Address the reader directly as "you"; include the writer as "we" where natural.',
            'Keep sentences short to medium; use a warm opener and a human close.',
            'Use at most one emoji where the channel allows it; never in formal or legal contexts.',
            'Use active voice and a positive framing of requests.',
            'Acknowledge the person before getting to the ask.',
        ],
        do: ['Open with a genuine, brief acknowledgement or thanks.', 'Keep it specific and sincere, not gushing.'],
        dont: [
            'Use cold, transactional phrasing ("Received. Will action.").',
            'Over-apologize or pile on exclamation marks.',
        ],
        exampleBefore: 'Request received and will be processed in due course.',
        exampleAfter: "Thanks for sending this over! I'll get it sorted for you today and let you know when it's done.",
    },
    {
        id: 'casual',
        label: 'Casual',
        definition: 'Relaxed, peer-to-peer prose with fragments and optional emoji, for team chat and DMs.',
        rules: [
            'Use contractions freely; sentence fragments are acceptable.',
            'Use everyday words and light slang; keep it readable.',
            'Keep messages short — one idea per message.',
            'Emoji and reactions are fine; do not overload (≤2 per message).',
            'Use active voice and second person.',
            'Avoid Latinate vocabulary, passive voice, and long subordinate chains.',
        ],
        do: [
            'Get to the point quickly and informally.',
            'Use a quick reaction or emoji instead of a "got it" message where natural.',
        ],
        dont: ['Use formal salutations or legalese.', 'Write a wall of text in one chat message.'],
        exampleBefore: 'Please be advised the deployment has concluded successfully.',
        exampleAfter: "Heads up — the deploy's done. ✅",
    },
    {
        id: 'conversational',
        label: 'Conversational',
        definition: 'Edited natural speech — reads like talking, but tightened — for blogs, docs, and UX copy.',
        rules: [
            'Write as you would speak, then tighten; read-aloud test must pass.',
            'Use contractions and second person ("you").',
            'Keep most sentences short; vary length deliberately to avoid a flat rhythm.',
            'Use plain verbs ("use", not "utilize") and concrete nouns.',
            'Use no corporate filler ("it is worth noting that", "in today\'s fast-paced world").',
            'One idea per paragraph; short paragraphs.',
        ],
        do: ['Address the reader directly and answer their likely next question.', 'Keep a clear point of view.'],
        dont: ['Use dense academic or legalese constructions.', 'Pad with throat-clearing introductions.'],
        exampleBefore: 'It is worth noting that utilization of this feature may facilitate enhanced productivity.',
        exampleAfter: "This feature saves you time — here's how to turn it on.",
    },
    {
        id: 'chat-message',
        label: 'Chat Message',
        definition: 'Ultra-brief, real-time, one-idea-per-message text for Slack/Teams and SMS.',
        rules: [
            'Limit each message to one idea or one ask.',
            'Lead with the ask, then any context ("Could you review X by Friday? Context: …").',
            'Use fragments and contractions; full grammar is optional.',
            'Keep it under ~3 lines; thread longer detail rather than fragmenting the channel.',
            'Emoji reactions stand in for "got it" / acknowledgement.',
            'Do not use as a permanent record of decisions.',
        ],
        do: ['Front-load the request so a busy reader sees it first.', 'Use threads for follow-up detail.'],
        dont: ['Send a lone "Hey" with no content.', 'Split one thought across many separate messages.'],
        exampleBefore: "Hi! Are you there? I had a question. It's about the budget. When you have time. Thanks!",
        exampleAfter: 'Could you review the budget draft by Friday? Quick — mainly the Q3 column. Thanks!',
    },
    {
        id: 'email',
        label: 'Email',
        definition: 'Structured async message with a clear subject, greeting, single ask, and close.',
        rules: [
            'Provide a specific, scannable subject line that states the topic and any action.',
            'Use a greeting, then state the purpose/ask in the first two lines (Bottom Line Up Front (BLUF)).',
            'Cover one topic per email; split unrelated topics into separate emails.',
            'Keep paragraphs short; use a short bulleted list for multiple items.',
            'End with a clear next step, owner, and deadline, then a courteous sign-off.',
            'Default to a semi-formal register; expand abbreviations as "Full Name (ABBR)".',
        ],
        do: ['Put the ask before the background.', 'Name what you need and by when.'],
        dont: ['Bury the request at the bottom.', 'Mix several unrelated asks in one thread.'],
        exampleBefore: 'Subject: hi — (three paragraphs of context, then an ask in the last line)',
        exampleAfter:
            'Subject: Need sign-off on release plan by Thu — Hi Sam, I need your approval on the attached release plan by Thursday to keep the Friday slot. Key change: rollback now automated. Details below. Thanks, Alex',
    },
    {
        id: 'technical',
        label: 'Technical',
        definition:
            'Precise, unambiguous, reproducible prose for specs, Application Programming Interfaces (APIs), and runbooks.',
        rules: [
            'Use exact, consistent terminology; define each abbreviation as "Full Name (ABBR)" on first use.',
            'Use the imperative mood for steps ("Run", "Set", "Create").',
            'State preconditions, inputs, outputs, and error/edge cases explicitly.',
            'Use present tense for behavior ("Returns the user object", not "This will return…").',
            'Avoid subjective language ("useful", "simply", "easy").',
            'Use code formatting for identifiers, commands, and values.',
        ],
        do: ['Make every instruction reproducible and verifiable.', 'State assumptions and version constraints.'],
        dont: ['Use marketing adjectives or hedges.', 'Leave terms undefined or ambiguous.'],
        exampleBefore: 'This handy method does the user lookup thing and is super fast.',
        exampleAfter:
            '`getUser(id)` returns the `User` for the given identifier, or `null` if none exists. Time complexity is O(1) on the indexed `id` column.',
    },
    {
        id: 'instructional',
        label: 'Instructional',
        definition: 'Step-by-step, second-person, imperative prose for tutorials, how-tos, and user guides.',
        rules: [
            'Use numbered steps in the order the reader performs them.',
            'Start each step with an imperative verb ("Click", "Run", "Open").',
            'Use second person ("you") throughout.',
            'State prerequisites first and the success criterion at the end.',
            'Keep one action per step; split compound actions.',
            'Avoid conceptual digressions; link them out instead.',
        ],
        do: ['Tell the reader what they will achieve before the steps.', 'State how to confirm each step worked.'],
        dont: ['Assume prior knowledge or skip setup.', 'Mix explanation into the step list.'],
        exampleBefore: "You'll want to deal with the config and then it should basically work after that.",
        exampleAfter:
            '1. Open `config.yaml`. 2. Set `enabled: true`. 3. Save and run `make reload`. You should see `status: active` in the output.',
    },
    {
        id: 'academic',
        label: 'Academic',
        definition: 'Evidence-based, cited, hedged, objective prose for papers and research write-ups.',
        rules: [
            'Support claims with evidence and explicit citations.',
            'Use measured, hedged language for uncertain claims ("suggests", "indicates").',
            'Use third person and an objective stance; avoid first-person opinion where the field expects it.',
            'Define discipline terms; allow longer, subordinated sentences.',
            'Distinguish your findings from prior work and from interpretation.',
            'Use no contractions, slang, emoji, or rhetorical questions.',
        ],
        do: ['Attribute every external claim to a source.', 'Separate results from discussion/interpretation.'],
        dont: [
            'Overstate certainty or generalize beyond the evidence.',
            'Use casual or persuasive marketing language.',
        ],
        exampleBefore: 'Our method is obviously the best and totally solves the problem.',
        exampleAfter:
            'The proposed method reduced error by 12% on the benchmark (Table 3), suggesting improved robustness, though generalization to other domains remains untested.',
    },
    {
        id: 'journalistic',
        label: 'Journalistic',
        definition: 'Fact-first, attributed prose built on the inverted pyramid and the 5 Ws + How.',
        rules: [
            'Lead with the single most important fact (inverted pyramid); never bury the lead.',
            'Cover Who, What, When, Where, Why, and How early.',
            'Keep paragraphs short (1–3 sentences) and details in descending importance.',
            'Attribute claims to a named source ("the team says", "according to the report").',
            'Use concise, AP-style language; prioritize accuracy and brevity.',
            'State facts, not opinion or persuasion.',
        ],
        do: ['Put the conclusion and impact in the first sentence.', 'Attribute every non-obvious claim.'],
        dont: ['Withhold the conclusion for suspense.', 'Inject opinion or a call to action.'],
        exampleBefore:
            'Let me walk you through some background before getting to what actually happened with the outage.',
        exampleAfter:
            'An API outage began at 09:14 UTC and lasted 42 minutes, affecting EU customers; the cause was an expired certificate, the team says. Service was fully restored by 09:56 UTC.',
    },
    {
        id: 'marketing',
        label: 'Marketing',
        definition: 'Benefit-led, persuasive, brand-voiced prose with a clear call to action.',
        rules: [
            'Lead with the benefit to the reader, not the feature.',
            'Use vivid, active language and concrete claims; avoid empty superlatives.',
            'Keep sentences punchy; vary rhythm; one core message.',
            'End with a single, specific call to action.',
            'Back any claim with a specific (number, proof, example) where possible.',
            "Match the brand voice; avoid jargon the audience won't know.",
        ],
        do: ['Translate every feature into a "so you can…" benefit.', 'Give one clear next action.'],
        dont: [
            'Stack unsupported superlatives ("best-in-class", "revolutionary").',
            'Add multiple competing calls to action.',
        ],
        exampleBefore: 'Our app has many features and advanced technology and is very good.',
        exampleAfter:
            'Ship releases in minutes, not hours — automated rollbacks have your back. Start your free trial today.',
    },
    {
        id: 'persuasive',
        label: 'Persuasive',
        definition: 'Argues a position and builds to an action using structured reasoning and evidence.',
        rules: [
            'State the position (claim) clearly at the start.',
            'Support it with reasons and evidence, strongest first.',
            'Acknowledge the main counter-argument and address it.',
            'Use reasons and facts, not feelings or pressure.',
            'Build to one specific recommended action.',
            'Keep a respectful, confident register; no manipulation or false urgency.',
        ],
        do: ['Pair each claim with evidence.', 'Close with the concrete ask.'],
        dont: ['Use manipulation, fear, or hidden assumptions.', 'Ignore the obvious objection.'],
        exampleBefore: 'We should just do it my way, trust me.',
        exampleAfter:
            'We should adopt the managed queue. It removes 8 hours/week of ops toil (reason 1) and improves reliability (reason 2); the migration risk is bounded by a phased rollout (objection addressed). I propose we start the pilot next sprint.',
    },
    {
        id: 'executive',
        label: 'Executive',
        definition:
            'Decision-first, concise prose that leads with the answer (Bottom Line Up Front (BLUF)) and quantifies.',
        rules: [
            'Lead with the answer, decision, or recommendation in the first sentence.',
            'Quantify impact and cost; give the "so what" before any detail.',
            'Keep it short; one screen or less.',
            'Avoid jargon dumps and low-level how-to detail.',
            'Use bullet points for options or trade-offs.',
            'State what you need from the reader (decision, approval, resource).',
        ],
        do: ['Put the recommendation and the ask at the top.', 'Summarize trade-offs in a line each.'],
        dont: ['Make the reader hunt for the conclusion.', 'Drown the message in implementation detail.'],
        exampleBefore: "Here's a lot of technical background, and at the end, a small recommendation.",
        exampleAfter:
            'Recommendation: approve the managed queue migration ($1,200/mo, payback in 2 quarters, removes our top reliability risk). I need a go/no-go by Friday. Details and risks below.',
    },
    {
        id: 'documentation',
        label: 'Documentation',
        definition: 'Findable, scannable, task- or reference-oriented prose for product and internal docs.',
        rules: [
            'Use sentence-case, descriptive headings that aid scanning and search.',
            'Use consistent terminology for the same concept throughout.',
            'Use active voice and present tense.',
            'Pick one Diátaxis mode per document (tutorial, how-to, reference, or explanation) and do not mix.',
            'Keep paragraphs short; use lists and tables for structured data.',
            'Assign an owner and keep content current; remove stale claims.',
        ],
        do: [
            'Make headings answer "what will I find here?".',
            'Cross-link related pages instead of repeating content.',
        ],
        dont: ['Mix tutorial and reference styles in one page.', 'Use emotional or persuasive language.'],
        exampleBefore: 'Stuff about the API and some other things you might need maybe.',
        exampleAfter:
            '## Authenticate a request — Send the API key in the `Authorization` header. See [Rate limits](#rate-limits) for quotas.',
    },
    {
        id: 'social-media',
        label: 'Social Media',
        definition: 'Hook-first, platform-native, scannable prose for LinkedIn, X, Threads, and Instagram.',
        rules: [
            'Open with a hook in the first one or two lines (before any "see more" cutoff).',
            'Keep it scannable: short lines, line breaks, no dense paragraphs.',
            'Use a platform-native voice; match formality to the platform.',
            'One core idea per post; thread for depth.',
            'Use few hashtags (≤3–5) and avoid engagement-bait phrasing.',
            'End with a genuine prompt or takeaway, not "like and share".',
        ],
        do: ['Front-load the value or the surprising claim.', 'Write a clear point of view.'],
        dont: ['Bury the hook below the fold.', 'Use generic AI-tells or engagement bait.'],
        exampleBefore:
            "In today's fast-paced world, I wanted to share some thoughts on a topic that I think is pretty important to a lot of people.",
        exampleAfter:
            "I deleted 40% of our tests last week. Coverage went up. Here's why fewer, better tests beat a wall of brittle ones: 🧵",
    },
    {
        id: 'community',
        label: 'Community',
        definition: 'Peer-to-peer, norm-aware, reciprocal prose for forums, Stack Overflow, and open-source.',
        rules: [
            'Show you searched first; reference what you already tried.',
            'Give enough context for others to reproduce or understand the situation.',
            'Be specific and reciprocal; offer to share the resolution.',
            "Follow the community's stated norms and code of conduct.",
            'Stay courteous — you are asking for help, not demanding results.',
            'Use a minimal reproducible example where relevant.',
        ],
        do: ['State the goal, what you tried, and the exact blocker.', 'Thank responders and post the final fix.'],
        dont: ['Broadcast or demand; ignore community rules.', 'Post a vague "it doesn\'t work" with no detail.'],
        exampleBefore: "This doesn't work. Fix it.",
        exampleAfter:
            "Goal: parse ISO dates in Python 3.12. I tried `datetime.fromisoformat(s)` but it raises `ValueError` on `2026-06-21Z`. Minimal repro below. What's the right way to handle the trailing `Z`?",
    },
    {
        id: 'support',
        label: 'Support',
        definition: 'Empathetic and solution-focused prose, plain and reassuring, with no jargon or blame.',
        rules: [
            "Acknowledge the problem and the person's frustration first.",
            'Use plain, jargon-free language; define any term you must use.',
            'Give a clear, concrete next step or fix.',
            'Never blame the customer or other teams.',
            'Set a realistic expectation (what happens next, by when).',
            'Keep a calm, reassuring register even under pressure.',
        ],
        do: ['Lead with empathy, then move to the fix.', 'Confirm the resolution and how to follow up.'],
        dont: ['Use internal jargon or shorthand.', '"as per our policy" without explaining what it means for them.'],
        exampleBefore: "That's not a bug, you're using it wrong. See the docs.",
        exampleAfter:
            "Sorry for the trouble — I can see why that's confusing. Here's the fix: go to Settings → Sync and toggle it on. I'll stay on this until it's working for you.",
    },
    {
        id: 'customer-facing',
        label: 'Customer-facing',
        definition: 'Brand-consistent, courteous, clear, jargon-free prose for any external touchpoint.',
        rules: [
            'Use accessible, jargon-free language and a positive framing.',
            'Stay brand-consistent and courteous throughout.',
            'Be clear about what the customer gets and what to do next.',
            'Avoid internal shorthand, team names, and ticket jargon.',
            'Take responsibility on behalf of the company; never blame the customer.',
            'Expand any unavoidable abbreviation as "Full Name (ABBR)".',
        ],
        do: ['Write as one helpful human to another.', 'State the outcome and next step plainly.'],
        dont: ['Leak internal jargon or process detail.', 'Use defensive or legalistic phrasing.'],
        exampleBefore: 'Per the SLA, the SEV-2 was triaged by L2 and routed to the BU owner.',
        exampleAfter:
            "Thanks for your patience. Our team has looked into the issue and a fix is rolling out today — you don't need to do anything.",
    },
    {
        id: 'public-announcement',
        label: 'Public Announcement',
        definition: 'Clear, authoritative, unambiguous prose for outages, launches, and policy notices.',
        rules: [
            'Lead with what happened (or what is changing) and its impact.',
            'State the next step or what the reader should do.',
            'Use direct, factual, structured language; no jargon.',
            'Provide a single source of truth and where to get updates.',
            'Give timestamps and scope (who is affected) explicitly.',
            'Keep a calm, authoritative register; no banter or speculation.',
        ],
        do: ['Put impact and action in the first lines.', 'Name a point of contact or status page.'],
        dont: ['Speculate about cause before it is confirmed.', 'Use casual or humorous asides.'],
        exampleBefore: "Hey all, something's up with the site, looking into it, more soon maybe!",
        exampleAfter:
            'Service disruption (09:14–09:56 UTC): EU customers could not log in. The cause is identified and a fix is deployed. We are monitoring. Updates: status.example.com.',
    },
    {
        id: 'storytelling',
        label: 'Storytelling',
        definition:
            'Narrative-arc prose with concrete detail, emotion, and varied rhythm, for blogs, talks, and case studies.',
        rules: [
            'Build a clear arc: setup, tension/turn, resolution, and takeaway.',
            'Use concrete, sensory detail and specific names, dates, and numbers.',
            'Vary sentence and paragraph length deliberately for rhythm.',
            'Show through scenes and examples, not abstract summary.',
            "Keep one through-line; cut tangents that don't serve it.",
            'Land a single clear point or lesson at the end.',
        ],
        do: [
            'Open with a specific moment or scene, not a thesis statement.',
            'Make the stakes and the change concrete.',
        ],
        dont: ['Use generic, detail-free generalities.', 'Use a flat, uniform sentence rhythm.'],
        exampleBefore: 'We had a problem with reliability and then we fixed it and things got better.',
        exampleAfter:
            "At 3 a.m. the pager went off for the fourth night running. By the time we found the expired cert, we'd lost two enterprise customers — and learned the hard way to alert on cert expiry 30 days out. Here's what we changed.",
    },
];
