import type { RuleOption } from '../model/types';

export const TONES: RuleOption[] = [
    {
        id: 'formal',
        label: 'Formal',
        definition: 'Reserved, respectful, and distant — the attitude of ceremony and authority.',
        rules: [
            'Keep an emotional distance; do not address feelings directly.',
            'Use respectful, deferential phrasing toward the reader.',
            'Use no contractions, slang, emoji, or exclamation marks.',
            'Keep wording measured and impersonal; favor third person where natural.',
            'Avoid humor and casual interjections entirely.',
        ],
        do: ['Maintain consistent courtesy and restraint.', 'State matters precisely and completely.'],
        dont: [
            'Use jokes, emoji, or warmth that breaks the distance.',
            'Address the reader by a nickname or familiar form.',
        ],
        exampleBefore: "Hey, just letting you know we got your thing and we'll deal with it soon!",
        exampleAfter: 'We acknowledge receipt of your request and will respond in due course.',
    },
    {
        id: 'professional',
        label: 'Professional',
        definition: 'Competent and composed — the default workplace attitude.',
        rules: [
            'Project competence and calm; no overstatement.',
            'Stay courteous and even, neither cold nor effusive.',
            'Use measured word choice; avoid slang and emotional intensifiers.',
            'Keep the focus on the task and the outcome.',
            'Allow light contractions; no emoji in formal threads.',
        ],
        do: ['Acknowledge briefly, then move to substance.', 'Keep a steady, reliable register.'],
        dont: ['Sound either robotic or overly chummy.', 'Let emotion color factual statements.'],
        exampleBefore: "OMG this is such a mess, I have no idea what's going on here!!",
        exampleAfter: "There's an issue here I want to flag. I'll outline what I'm seeing and propose a next step.",
    },
    {
        id: 'neutral',
        label: 'Neutral',
        definition: 'Detached and even — no emotional coloring at all.',
        rules: [
            'Carry no emotion, praise, or blame.',
            'Keep word choice denotative and value-free.',
            'Use no intensifiers ("very", "amazing", "terrible").',
            'State facts; let the reader draw conclusions.',
            'Use no emoji or exclamation marks.',
        ],
        do: ['Report what happened plainly.', 'Quantify instead of qualifying.'],
        dont: ['Editorialize or signal an attitude.', 'Soften or dramatize the facts.'],
        exampleBefore: 'Unfortunately the build sadly failed again, which is really frustrating.',
        exampleAfter: 'The build failed at 14:02 on commit a1b2c3d; the error was a missing dependency.',
    },
    {
        id: 'friendly',
        label: 'Friendly',
        definition: 'Approachable and kind — an open, welcoming attitude.',
        rules: [
            'Address the reader warmly and personally.',
            'Use everyday words and light contractions.',
            'Keep the framing positive and helpful.',
            'One emoji is acceptable where the channel allows it.',
            'Avoid undercutting serious content with too much breeziness.',
        ],
        do: ['Open with a genuine, brief greeting.', 'Offer help proactively.'],
        dont: ['Be so casual that seriousness is lost.', 'Force friendliness in a crisis or formal complaint.'],
        exampleBefore: 'Submit the form. Wrong fields will be rejected.',
        exampleAfter: "Happy to help you get this submitted! Just double-check the email field and you're all set.",
    },
    {
        id: 'warm',
        label: 'Warm',
        definition: 'Caring and personal — genuine appreciation and care for the reader.',
        rules: [
            'Acknowledge the person and their effort or situation.',
            'Use caring, positive word choice and a human close.',
            'Be specific and genuine, not generic.',
            'Keep it sincere; avoid saccharine clichés.',
            'Do not over-apologize or gush.',
        ],
        do: ['Name what you appreciate specifically.', 'Sign off as a person, not a department.'],
        dont: ['Use empty platitudes ("we value you as a customer").', 'Pile on exclamation marks.'],
        exampleBefore: 'Received. Will action.',
        exampleAfter:
            "Thanks so much for sending this over — I really appreciate it. I'll take care of it today and let you know once it's done.",
    },
    {
        id: 'empathetic',
        label: 'Empathetic',
        definition: "Validating — acknowledges and respects the reader's feelings.",
        rules: [
            "Name and validate the reader's feeling specifically.",
            'Show you understand the impact on them.',
            'Use plain, caring language; no defensiveness.',
            "Pair empathy with a concrete next step so it isn't hollow.",
            'Avoid minimizing words ("just", "only", "no big deal").',
        ],
        do: ['Acknowledge the impact before explaining or fixing.', 'Be specific about what you understand.'],
        dont: ['Say "sorry for any inconvenience" or "but" after "sorry".', 'Offer hollow empathy with no action.'],
        exampleBefore: 'Sorry for any inconvenience. Please see attached.',
        exampleAfter:
            "I'm sorry — losing a morning to this is genuinely frustrating, and you were right to flag it. Here's exactly what I'm doing to fix it now.",
    },
    {
        id: 'confident',
        label: 'Confident',
        definition: 'Assured and decisive — clear conviction without arrogance.',
        rules: [
            'State the position or recommendation directly, without hedging.',
            'Remove filler hedges ("just", "maybe", "I think", "sort of").',
            'Back the claim with a reason or evidence.',
            'Keep it respectful; confidence is not dismissiveness.',
            'Use active voice and decisive verbs.',
        ],
        do: ['Lead with the clear recommendation.', 'Own the position while staying open to questions.'],
        dont: ['Tip into arrogance or talk down to the reader.', 'Hedge every sentence into vagueness.'],
        exampleBefore: "I'm not totally sure, but maybe we could possibly consider option B if that's okay?",
        exampleAfter:
            "I recommend option B. It's faster to ship and lowers our reliability risk. Happy to walk through the trade-offs.",
    },
    {
        id: 'assertive',
        label: 'Assertive',
        definition: 'Direct and boundary-setting — states the need or limit firmly and respectfully.',
        rules: [
            'State the ask, need, or boundary directly and early ("I need…", "We require…").',
            'Give a concrete deadline or condition where relevant.',
            'Be firm but respectful; no aggression or blame.',
            'Remove softeners that undercut the message ("sorry to bother", "if it\'s not too much trouble").',
            'Avoid passive-aggression and threats.',
        ],
        do: ['Make the boundary and the by-when explicit.', 'Stay calm and factual.'],
        dont: ['Apologize for having a reasonable need.', 'Use hostility, sarcasm, or ultimatums.'],
        exampleBefore: 'Sorry to keep bugging you, maybe whenever you get a sec could you possibly look at the lease?',
        exampleAfter:
            "I need the signed lease back by Thursday to hold the unit. Can you confirm you'll send it by then?",
    },
    {
        id: 'persuasive',
        label: 'Persuasive',
        definition: 'Motivating — moves the reader toward an action through reasons and benefit.',
        rules: [
            'Lead with the benefit to the reader.',
            'Support the ask with reasons and evidence, strongest first.',
            'Address the likely objection.',
            'Build to one clear action.',
            'Use reasons and facts, never manipulation or false urgency.',
        ],
        do: ['Frame the request around what the reader gains.', 'Close with the specific next step.'],
        dont: ['Use pressure tactics or hidden assumptions.', 'Overdo it until it reads as manipulative.'],
        exampleBefore: 'You should approve this because I want it.',
        exampleAfter:
            "Approving the repair now avoids a larger water-damage bill later and keeps the unit rentable. I've attached two quotes — can we proceed with the lower one this week?",
    },
    {
        id: 'educational',
        label: 'Educational',
        definition: 'Patient and explanatory — teaches without condescending.',
        rules: [
            'Explain the "why", not just the "what".',
            'Define terms before using them; build from what the reader knows.',
            'Use concrete examples and analogies.',
            'Keep a patient, encouraging register.',
            'Avoid condescending words ("simply", "just", "obviously", "everyone knows").',
        ],
        do: ['Check understanding and invite questions.', 'Use one clear example per concept.'],
        dont: ['Talk down or imply the reader should already know.', 'Dump jargon without explanation.'],
        exampleBefore: "Obviously you just use a hash map, it's trivial.",
        exampleAfter:
            "A hash map lets you look up a value by a key in roughly constant time. Here's a small example, and why it fits your case better than a list.",
    },
    {
        id: 'respectful',
        label: 'Respectful',
        definition: "Deferential and considerate — values the reader's standing and time.",
        rules: [
            "Acknowledge the reader's expertise, role, or time.",
            'Use courteous, considerate phrasing.',
            'Make requests, not demands; offer rather than impose.',
            'Avoid presumption and over-familiarity.',
            'Keep humility without servility.',
        ],
        do: ['Frame asks as requests and thank the reader for their time.', 'Defer to expertise where appropriate.'],
        dont: ['Be servile or self-deprecating to the point of weakness.', "Presume on the reader's time or goodwill."],
        exampleBefore: "Just do this for me, it's urgent.",
        exampleAfter:
            "I know your time is tight — when you have a moment, could you advise on the right approach here? I'd value your read on it.",
    },
    {
        id: 'enthusiastic',
        label: 'Enthusiastic',
        definition: 'Energetic and positive — genuine excitement and momentum.',
        rules: [
            'Convey genuine energy through verbs and specifics, not just exclamation marks.',
            'Keep enthusiasm grounded in a real reason or win.',
            'Use at most one or two exclamation marks; let the words carry energy.',
            'Stay sincere; avoid hype that outpaces reality.',
            'Match the energy to the occasion (never in a crisis).',
        ],
        do: ["Name the specific thing you're excited about.", 'Invite others to share the moment.'],
        dont: ['Use relentless exclamation marks or hype.', 'Sound insincere or exhausting.'],
        exampleBefore: 'We shipped the feature. It is now available.',
        exampleAfter:
            'We shipped it! 🎉 After three weeks of work, the new dashboard is live — and it loads twice as fast. Huge thanks to everyone who pitched in.',
    },
    {
        id: 'diplomatic',
        label: 'Diplomatic',
        definition: 'Tactful and balanced — manages disagreement without giving offense.',
        rules: [
            'Acknowledge the other view before presenting yours.',
            'Frame it as "us vs. the problem", not "me vs. you".',
            'Use measured, non-accusatory language; no "you always/never".',
            'Offer an alternative, not just a rejection.',
            "Stay specific so tact doesn't become evasive vagueness.",
        ],
        do: ['Find common ground first.', 'Disagree with the idea, not the person.'],
        dont: ['Become so vague that no position is stated.', 'Assign blame or use loaded language.'],
        exampleBefore: "Your plan is wrong and won't work.",
        exampleAfter:
            'I see the appeal of this approach. My one concern is the rollback path — could we combine your idea with a phased release to cover that?',
    },
    {
        id: 'collaborative',
        label: 'Collaborative',
        definition: 'Inclusive — invites shared ownership with "we" and "let\'s".',
        rules: [
            'Use inclusive language ("we", "let\'s", "our").',
            'Invite input rather than dictating.',
            'Frame problems as shared and solvable together.',
            "Credit others' contributions.",
            "Keep it genuine — don't manufacture false consensus.",
        ],
        do: ["Ask for the team's view on the path forward.", "Build on others' ideas explicitly."],
        dont: ["Pretend agreement that doesn't exist.", '"I decided" framing for shared work.'],
        exampleBefore: "I've decided we're doing it this way. Start tomorrow.",
        exampleAfter:
            "Here's a path I think could work — what would you change? Let's land on an approach together before we start.",
    },
    {
        id: 'casual',
        label: 'Casual',
        definition: 'Relaxed and informal — the attitude of talking to a peer.',
        rules: [
            'Keep it relaxed, with contractions and everyday words.',
            'Short and informal; fragments are fine.',
            'Light humor and emoji are acceptable where the channel allows.',
            'Skip formal salutations and sign-offs.',
            'Keep it appropriate to peers; not for formal or external settings.',
        ],
        do: ['Sound like a real person talking to a friend.', 'Keep it brief and low-ceremony.'],
        dont: ['Use this attitude with executives or in formal complaints.', 'Over-formalize ("Dear Sir/Madam").'],
        exampleBefore: 'Please be advised that I will be unavailable during the aforementioned period.',
        exampleAfter: "Heads up, I'll be out tomorrow — ping Sam if anything comes up.",
    },
    {
        id: 'humorous',
        label: 'Humorous',
        definition: 'Light and playful — uses humor to connect or lighten a moment.',
        rules: [
            "Keep humor light, kind, and inclusive — never at someone's expense.",
            'Make sure the core message still lands clearly.',
            'Avoid sarcasm that could be misread, and culture-specific in-jokes.',
            'Never use humor in a crisis, apology, or sensitive context.',
            'Keep it brief; one light touch, not a comedy routine.',
        ],
        do: [
            'Use a single playful line that fits the audience.',
            'Keep the information unambiguous despite the humor.',
        ],
        dont: ['Joke during incidents, layoffs, or apologies.', 'Use humor that could offend across cultures.'],
        exampleBefore: 'The coffee machine is broken. It will be repaired.',
        exampleAfter:
            'The coffee machine has filed for early retirement ☕️ — repair is scheduled for Thursday. Bring backup caffeine until then.',
    },
    {
        id: 'serious',
        label: 'Serious',
        definition: 'Grave and focused — signals that the matter carries weight.',
        rules: [
            'Treat the subject with appropriate gravity; no jokes or banter.',
            'State facts and stakes plainly and directly.',
            'Avoid minimizing language ("just", "no big deal").',
            'Keep emotion controlled; convey weight through clarity, not drama.',
            'Be specific about consequences and required actions.',
        ],
        do: ['State the stakes and the required action clearly.', 'Stay calm and factual under gravity.'],
        dont: ['Use humor, emoji, or casual asides.', 'Downplay the severity.'],
        exampleBefore: "Hey, tiny thing — looks like maybe some data leaked? No biggie, we'll check it out 🙂",
        exampleAfter:
            'We have confirmed unauthorized access to a customer data store. This is a security incident. Do not discuss it externally; follow the incident process and await instructions from the response lead.',
    },
    {
        id: 'supportive',
        label: 'Supportive',
        definition: 'Encouraging — builds the reader up while staying honest.',
        rules: [
            'Recognize effort and progress specifically.',
            'Pair encouragement with honest, actionable guidance.',
            'Frame setbacks as fixable and next steps as achievable.',
            'Use a warm, believing-in-you register.',
            'Don\'t let support soften the message into vagueness (avoid "ruinous empathy").',
        ],
        do: ['Name a specific strength, then the next step.', 'Offer concrete help.'],
        dont: ['Avoid the necessary candid point.', 'Praise so generically it carries no information.'],
        exampleBefore: "This isn't good enough, do it again.",
        exampleAfter:
            "You've made real progress on the structure here. The next step is tightening the error handling — want to pair on it? You're closer than you think.",
    },
    {
        id: 'reassuring',
        label: 'Reassuring',
        definition: 'Calming — reduces worry with honesty and a clear plan.',
        rules: [
            'Acknowledge the concern directly.',
            'State what is known, what is being done, and what to expect next.',
            "Be honest; never offer comfort that isn't grounded in fact.",
            'Use a calm, steady register.',
            'Give a concrete next checkpoint or update time.',
        ],
        do: ['Pair calm with a clear plan and timeline.', 'Tell the reader what they need to do, if anything.'],
        dont: ['Make false promises or hollow comfort.', 'Be vague about what happens next.'],
        exampleBefore: "Don't worry, everything's probably fine, it'll sort itself out.",
        exampleAfter:
            "We've identified the cause and a fix is deploying now. Most users should see recovery within 15 minutes; we'll post the next update by 10:30. Your data is safe.",
    },
    {
        id: 'authoritative',
        label: 'Authoritative',
        definition: 'Expert and definitive — speaks as the trusted source on the matter.',
        rules: [
            'State guidance definitively and unambiguously.',
            'Back authority with correctness and clarity, not bluster.',
            'Use precise terminology consistently.',
            'Avoid hedging on settled matters; flag genuine uncertainty explicitly.',
            'Keep it concise; do not over-explain.',
        ],
        do: ['Give the definitive recommendation or rule.', 'Cite the standard or source where relevant.'],
        dont: ['Sound arrogant or closed to legitimate questions.', 'Present opinion as settled fact.'],
        exampleBefore: 'I guess maybe you should probably use HTTPS, if you want?',
        exampleAfter:
            'Use HTTPS for all endpoints. Plain HTTP is not permitted in production; requests over HTTP are rejected at the gateway.',
    },
    {
        id: 'executive',
        label: 'Executive',
        definition: 'Concise, decisive, big-picture — speaks to leaders in terms of outcomes.',
        rules: [
            'Lead with the decision, recommendation, or headline outcome.',
            'Quantify impact; give the "so what" before any detail.',
            'Be brief and high-level; omit low-level mechanics.',
            'State clearly what is needed (decision, approval, resource).',
            'Use confident, plain language; no jargon dumps.',
        ],
        do: ['Put the bottom line first.', 'Summarize trade-offs in one line each.'],
        dont: [
            'Bury the recommendation under detail.',
            "Dismiss detail entirely when it's load-bearing for the decision.",
        ],
        exampleBefore: 'Lots of background, and somewhere in here is a recommendation.',
        exampleAfter:
            'Bottom line: we should approve the migration — $1,200/mo, payback in two quarters, removes our top reliability risk. I need a decision by Friday.',
    },
];
