import type { ValueSet } from '../model/types';

export const VALUE_SETS: ValueSet[] = [
    {
        id: 'programming-language',
        label: 'Programming language',
        allowCustom: true,
        values: [
            'Java',
            'JavaScript',
            'TypeScript',
            'Python',
            'Go',
            'C#',
            'C++',
            'C',
            'Rust',
            'Kotlin',
            'Swift',
            'Ruby',
            'PHP',
            'SQL',
            'Scala',
            'Bash',
        ],
    },
    { id: 'output-format', label: 'Output format', allowCustom: false, values: ['PlainText', 'Markdown'] },
    {
        id: 'sql-dialect',
        label: 'SQL dialect',
        allowCustom: true,
        values: ['PostgreSQL', 'MySQL', 'SQLite', 'SQL Server', 'Oracle'],
    },
    {
        id: 'aspect-ratio',
        label: 'Aspect ratio',
        allowCustom: true,
        values: [
            '1:1 (square)',
            '16:9 (widescreen / landscape)',
            '9:16 (vertical / portrait)',
            '4:3 (standard)',
            '3:4 (portrait)',
            '21:9 (cinematic ultrawide)',
            '3:2 (photo landscape)',
            '2:3 (photo portrait)',
        ],
    },
    {
        id: 'image-style',
        label: 'Image style',
        allowCustom: true,
        values: [
            'Photorealistic',
            'Cinematic',
            'Portrait photography',
            'Landscape photography',
            'Studio product shot',
            'Illustration',
            'Watercolor',
            'Oil painting',
            'Line art / sketch',
            'Anime',
            'Cartoon',
            '3D render',
            'Pixel art',
            'Flat / vector',
            'Concept art',
            'Vintage / film',
        ],
    },
    {
        id: 'audience',
        label: 'Audience',
        allowCustom: true,
        values: [
            'General / non-technical',
            'Beginner',
            'Intermediate',
            'Expert / technical',
            'Software engineers',
            'Executives / leadership',
            'Stakeholders',
            'Customers / end users',
            'Students / learners',
            'Children',
        ],
    },
    {
        id: 'reading-level',
        label: 'Reading level',
        allowCustom: true,
        values: [
            'Elementary (Grade 5)',
            'Middle school (Grade 8)',
            'High school (Grade 10–12)',
            'General adult',
            'College / professional',
            'Expert',
        ],
    },
    {
        id: 'length',
        label: 'Target length',
        allowCustom: true,
        values: [
            'One sentence',
            'One short paragraph',
            '2–3 paragraphs',
            'About 150 words',
            'About 300 words',
            'About 500 words',
            'Concise (as short as possible)',
            'Detailed (as long as needed)',
        ],
    },
    {
        id: 'language',
        label: 'Natural language (locale)',
        allowCustom: true,
        values: [
            'English (US)',
            'English (UK)',
            'Spanish',
            'French',
            'German',
            'Italian',
            'Portuguese (Brazil)',
            'Dutch',
            'Polish',
            'Ukrainian',
            'Russian',
            'Chinese (Simplified)',
            'Japanese',
            'Korean',
            'Arabic',
            'Hindi',
            'Czech',
            'Croatian',
            'Serbian',
            'Montenegrian',
            'Slovenian',
            'Slovak',
        ],
    },
    {
        id: 'diagram-type',
        label: 'Diagram type',
        allowCustom: true,
        values: [
            'Flowchart',
            'Sequence diagram',
            'Class diagram',
            'State diagram',
            'Entity-Relationship (ER) diagram',
            'Gantt chart',
            'Mind map',
            'C4 (Context / Container / Component)',
            'Architecture diagram',
            'Network diagram',
        ],
    },
    {
        id: 'diagram-tool',
        label: 'Diagram tool / syntax',
        allowCustom: false,
        values: ['Mermaid', 'draw.io (diagrams.net)'],
    },
    {
        id: 'image-model',
        label: 'Image model',
        allowCustom: false,
        values: [
            'Nano Banana Pro',
            'Qwen Image',
            'Qwen Image Edit 2511',
            'FLUX.2',
            'FLUX.2 Klein',
            'GPT Image',
            'Stable Diffusion',
            'JoyAI',
        ],
    },
    {
        id: 'video-model',
        label: 'Video model',
        allowCustom: false,
        values: [
            'Veo',
            'Kling',
            'Runway',
            'Seedance',
            'Hailuo',
            'Luma',
            'Pika',
            'Wan (local)',
            'Wan (API)',
            'HunyuanVideo',
            'LTX',
            'CogVideoX',
            'Mochi',
        ],
    },
    {
        id: 'target-agent',
        label: 'Target AI coding agent',
        allowCustom: true,
        values: [
            'Claude Code',
            'OpenAI Codex',
            'GitHub Copilot',
            'OpenCode',
            'Amazon Kiro',
            'JetBrains Junie',
            'Cursor',
            'Windsurf',
        ],
    },
    {
        id: 'install-scope',
        label: 'Install scope',
        allowCustom: false,
        values: ['Project (committed, team-shared)', 'User / global (personal, cross-project)'],
    },
    {
        id: 'execution-context',
        label: 'Execution mode',
        allowCustom: false,
        values: ['ChatBot (paste input)', 'AI Agent (point at repo/folder/scope)'],
    },
    {
        id: 'output-target',
        label: 'Documentation output target',
        allowCustom: false,
        values: ['Temporary / working docs (git-ignored)', 'Committed project documentation (docs/ + README)'],
    },
    {
        id: 'summary-form',
        label: 'Summary form',
        allowCustom: true,
        values: [
            'Executive summary',
            'Key points (bullets)',
            "One-line TL;DR (Too Long; Didn't Read)",
            'Abstract',
            'Paragraph summary',
        ],
    },
    {
        id: 'test-framework',
        label: 'Test framework',
        allowCustom: true,
        values: [
            'JUnit (Java)',
            'pytest (Python)',
            'Jest (JavaScript/TypeScript)',
            'Vitest (JavaScript/TypeScript)',
            'go test (Go)',
            'Cargo test (Rust)',
            'RSpec (Ruby)',
            'PHPUnit (PHP)',
            'xUnit (C#)',
            'NUnit (C#)',
        ],
    },
    // ─── Addendum — value-sets referenced by Phase 2 prompt content ───────────
    {
        id: 'api-style',
        label: 'API style',
        allowCustom: true,
        values: ['REST', 'GraphQL', 'gRPC', 'WebSocket', 'SOAP'],
    },
    {
        id: 'data-format',
        label: 'Data format',
        allowCustom: true,
        values: ['JSON', 'YAML', 'XML', 'CSV', 'TOML', 'Protocol Buffers'],
    },
    {
        id: 'regex-flavor',
        label: 'Regular-expression flavor',
        allowCustom: true,
        values: ['PCRE (Perl-Compatible)', 'JavaScript', 'Python (re)', 'Java', 'Go (RE2)', 'POSIX ERE'],
    },
    {
        id: 'cicd-platform',
        label: 'Continuous Integration / Continuous Delivery (CI/CD) platform',
        allowCustom: true,
        values: ['GitHub Actions', 'GitLab CI/CD', 'Jenkins', 'CircleCI', 'Azure Pipelines', 'Bitbucket Pipelines'],
    },
    {
        id: 'diataxis-mode',
        label: 'Documentation mode (Diataxis)',
        allowCustom: false,
        values: ['Tutorial', 'How-to guide', 'Reference', 'Explanation'],
    },
    {
        id: 'headline-kind',
        label: 'Headline kind',
        allowCustom: true,
        values: ['Headlines', 'Taglines', 'Subject lines'],
    },
    {
        id: 'social-platform',
        label: 'Social platform',
        allowCustom: true,
        values: ['LinkedIn', 'X', 'Threads', 'Instagram', 'Reddit', 'Facebook'],
    },
    {
        id: 'audience-level',
        label: 'Audience level',
        allowCustom: true,
        values: ['Non-technical / general', 'Beginner', 'Intermediate', 'Expert', 'Executive / leadership'],
    },
    {
        id: 'simplify-audience',
        label: 'Simplify for audience',
        allowCustom: true,
        values: ['Non-native English speakers', 'Children (age 8-10)', 'Non-experts', 'Busy executives'],
    },
    {
        id: 'scenario-type',
        label: 'Scenario type',
        allowCustom: true,
        values: ['Best case', 'Worst case', 'Most likely', 'Edge case'],
    },
    {
        id: 'prioritization-model',
        label: 'Prioritization model',
        allowCustom: false,
        values: [
            'RICE (Reach, Impact, Confidence, Effort)',
            'ICE (Impact, Confidence, Ease)',
            "MoSCoW (Must, Should, Could, Won't)",
            'WSJF (Weighted Shortest Job First)',
            'Eisenhower Matrix',
        ],
    },
    {
        id: 'status-format',
        label: 'Status-update format',
        allowCustom: true,
        values: ['Done / Doing / Blockers', 'Bottom Line Up Front (BLUF)', 'Red / Amber / Green (RAG)'],
    },
    {
        id: 'synthesis-output-kind',
        label: 'Synthesis output kind',
        allowCustom: true,
        values: ['Executive brief', 'Summary', 'Comparison matrix', 'Annotated bibliography'],
    },
    {
        id: 'editpass-apply-mode',
        label: 'Edit-pass apply mode',
        allowCustom: false,
        values: ['Suggest only (report)', 'Apply in place'],
    },
];
