import {
    LINUX_APT_UPDATE,
    LINUX_APT_VERIFY,
    LINUX_BREW_DEPS_APT,
    LINUX_BREW_DEPS_DNF,
    LINUX_BREW_INSTALL,
    LINUX_BREW_PATH,
    LINUX_BREW_VERIFY,
    LINUX_DNF_UPDATE,
    LINUX_DNF_VERIFY,
    LINUX_ENV_ADD_TO_PATH,
    LINUX_ENV_EXPORT_EXAMPLE,
    LINUX_ENV_JAVA_HOME,
    LINUX_ENV_RELOAD,
    LINUX_FLATPAK_FLATHUB,
    LINUX_FLATPAK_INSTALL_APT,
    LINUX_FLATPAK_INSTALL_DNF,
    LINUX_FLATPAK_INSTALL_PACMAN,
    LINUX_FLATPAK_INSTALL_ZYPPER,
    LINUX_FLATPAK_VERIFY,
    LINUX_PACMAN_UPDATE,
    LINUX_PACMAN_VERIFY,
    LINUX_SNAP_INSTALL_APT,
    LINUX_SNAP_INSTALL_DNF,
    LINUX_SNAP_INSTALL_PACMAN,
    LINUX_SNAP_INSTALL_ZYPPER,
    LINUX_SNAP_VERIFY,
    LINUX_ZYPPER_UPDATE,
    LINUX_ZYPPER_VERIFY,
} from '@/common/linux-utils';

describe('linux-utils constants', () => {
    it.each([
        ['LINUX_APT_VERIFY', LINUX_APT_VERIFY],
        ['LINUX_APT_UPDATE', LINUX_APT_UPDATE],
        ['LINUX_DNF_VERIFY', LINUX_DNF_VERIFY],
        ['LINUX_DNF_UPDATE', LINUX_DNF_UPDATE],
        ['LINUX_PACMAN_VERIFY', LINUX_PACMAN_VERIFY],
        ['LINUX_PACMAN_UPDATE', LINUX_PACMAN_UPDATE],
        ['LINUX_ZYPPER_VERIFY', LINUX_ZYPPER_VERIFY],
        ['LINUX_ZYPPER_UPDATE', LINUX_ZYPPER_UPDATE],
        ['LINUX_FLATPAK_INSTALL_APT', LINUX_FLATPAK_INSTALL_APT],
        ['LINUX_FLATPAK_INSTALL_DNF', LINUX_FLATPAK_INSTALL_DNF],
        ['LINUX_FLATPAK_INSTALL_PACMAN', LINUX_FLATPAK_INSTALL_PACMAN],
        ['LINUX_FLATPAK_INSTALL_ZYPPER', LINUX_FLATPAK_INSTALL_ZYPPER],
        ['LINUX_FLATPAK_FLATHUB', LINUX_FLATPAK_FLATHUB],
        ['LINUX_FLATPAK_VERIFY', LINUX_FLATPAK_VERIFY],
        ['LINUX_SNAP_INSTALL_APT', LINUX_SNAP_INSTALL_APT],
        ['LINUX_SNAP_INSTALL_DNF', LINUX_SNAP_INSTALL_DNF],
        ['LINUX_SNAP_INSTALL_PACMAN', LINUX_SNAP_INSTALL_PACMAN],
        ['LINUX_SNAP_INSTALL_ZYPPER', LINUX_SNAP_INSTALL_ZYPPER],
        ['LINUX_SNAP_VERIFY', LINUX_SNAP_VERIFY],
        ['LINUX_BREW_DEPS_APT', LINUX_BREW_DEPS_APT],
        ['LINUX_BREW_DEPS_DNF', LINUX_BREW_DEPS_DNF],
        ['LINUX_BREW_INSTALL', LINUX_BREW_INSTALL],
        ['LINUX_BREW_PATH', LINUX_BREW_PATH],
        ['LINUX_BREW_VERIFY', LINUX_BREW_VERIFY],
        ['LINUX_ENV_EXPORT_EXAMPLE', LINUX_ENV_EXPORT_EXAMPLE],
        ['LINUX_ENV_ADD_TO_PATH', LINUX_ENV_ADD_TO_PATH],
        ['LINUX_ENV_JAVA_HOME', LINUX_ENV_JAVA_HOME],
        ['LINUX_ENV_RELOAD', LINUX_ENV_RELOAD],
    ])('%s is a non-empty string', (_name, value) => {
        expect(typeof value).toBe('string');
        expect(value.length).toBeGreaterThan(0);
    });

    it('LINUX_BREW_INSTALL contains Homebrew/install', () => {
        expect(LINUX_BREW_INSTALL).toContain('Homebrew/install');
    });

    it('LINUX_FLATPAK_FLATHUB contains flathub.org', () => {
        expect(LINUX_FLATPAK_FLATHUB).toContain('flathub.org');
    });

    it('LINUX_BREW_PATH contains linuxbrew', () => {
        expect(LINUX_BREW_PATH).toContain('linuxbrew');
    });

    it('LINUX_ENV_ADD_TO_PATH contains PATH', () => {
        expect(LINUX_ENV_ADD_TO_PATH).toContain('PATH');
    });
});
