import type { CatalogApp, CatalogManager, CatalogMethod, CatalogPlatform, LinuxDistro } from './apps-catalog-types';

// ─── Public types ─────────────────────────────────────────────────────────────

export type ScriptAction = 'install' | 'update' | 'remove';

export type FallbackMode = 'preferred-only' | 'fallback';

export interface BuilderConfig {
    platform: CatalogPlatform;
    linuxDistro?: LinuxDistro;
    managers: CatalogManager[];
    overrides: Record<string, CatalogManager>;
    fallbackMode: FallbackMode;
    selectedVersions: Record<string, string>;
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function getMethodsForPlatform(app: CatalogApp, config: BuilderConfig): CatalogMethod[] | undefined {
    if (config.platform === 'linux') {
        if (!config.linuxDistro) {
            throw new Error('linuxDistro is required when platform is linux');
        }
        const distroMethods = app.methods.linux?.[config.linuxDistro];
        return distroMethods && distroMethods.length > 0 ? distroMethods : undefined;
    }
    if (config.platform === 'macos') {
        const m = app.methods.macos;
        return m && m.length > 0 ? m : undefined;
    }
    const m = app.methods.windows;
    return m && m.length > 0 ? m : undefined;
}

function findMethodByManager(methods: CatalogMethod[], manager: CatalogManager): CatalogMethod | undefined {
    return methods.find((m) => m.manager === manager);
}

// ─── Exported pure functions ──────────────────────────────────────────────────

/**
 * Resolves which manager to use for app + config.
 *
 * Resolution order:
 *  1. Platform guard (app.platforms[platform] must be true)
 *  2. Parameterized guard (selectedVersions[app.id] required when app.parameterized)
 *  3. Per-app override (config.overrides[app.id]) — wins if manager has a method
 *  4. First manager in config.managers (priority list) that has a method
 *  5. If fallbackMode === 'fallback': first available manager for this platform
 *  6. null → app is skipped
 */
export function resolveManager(app: CatalogApp, config: BuilderConfig): CatalogManager | null {
    if (!app.platforms[config.platform]) return null;

    if (app.parameterized && !config.selectedVersions[app.id]) return null;

    const methods = getMethodsForPlatform(app, config);
    if (!methods) return null;

    const override = config.overrides[app.id];
    if (override && findMethodByManager(methods, override)) return override;

    for (const mgr of config.managers) {
        if (findMethodByManager(methods, mgr)) return mgr;
    }

    if (config.fallbackMode === 'fallback' && methods.length > 0) {
        return methods[0].manager;
    }

    return null;
}

/**
 * Extracts and returns the command string for the given action from a method.
 * Applies {version} substitution (all occurrences) when version is provided.
 * Returns null when the method has no command for that action.
 */
export function getCommand(method: CatalogMethod, action: ScriptAction, version?: string): string | null {
    const raw = action === 'install' ? method.install : action === 'update' ? method.update : method.remove;
    if (!raw) return null;
    return version !== undefined ? raw.replaceAll('{version}', version) : raw;
}

// ─── Internal skip-reason helper ──────────────────────────────────────────────

function skipReason(app: CatalogApp, config: BuilderConfig): string {
    if (!app.platforms[config.platform]) {
        return `# ${app.name}: no platform build — skipped`;
    }
    if (app.parameterized && !config.selectedVersions[app.id]) {
        return `# ${app.name}: no version selected — skipped`;
    }
    return `# ${app.name}: no preferred manager (fallback off) — skipped`;
}

// ─── Combined script builder ──────────────────────────────────────────────────

/**
 * Builds a single combined script (all apps in one file).
 * macOS/Linux → bash (.sh); Windows → PowerShell (.ps1).
 * Skipped apps and missing-command apps emit inline comment lines.
 */
export function buildCombinedScript(apps: CatalogApp[], action: ScriptAction, config: BuilderConfig): string {
    const lines: string[] = [];
    const isWindows = config.platform === 'windows';
    const label = action.toUpperCase();

    if (isWindows) {
        lines.push(`# ${label} — combined (PowerShell)`);
        lines.push('$ok=0;$fail=0');
    } else {
        lines.push('#!/usr/bin/env bash');
        lines.push(`# ${label} — combined, generated by dev.tools`);
        lines.push('set -uo pipefail; SUCCESS=0; FAILED=0');
        lines.push(
            'run_task(){ echo "▶ $1"; shift; if "$@"; then SUCCESS=$((SUCCESS+1)); else FAILED=$((FAILED+1)); fi; }',
        );
    }

    for (const app of apps) {
        const manager = resolveManager(app, config);
        if (!manager) {
            lines.push(skipReason(app, config));
            continue;
        }

        const methods = getMethodsForPlatform(app, config)!;
        const method = findMethodByManager(methods, manager)!;
        const version = app.parameterized ? config.selectedVersions[app.id] : undefined;
        const cmd = getCommand(method, action, version);

        if (!cmd) {
            lines.push(`# ${app.name}: no ${action} command — skipped`);
            continue;
        }

        if (isWindows) {
            lines.push(`Write-Host "${action} ${app.name}"; ${cmd}`);
        } else {
            lines.push(`run_task "${action} ${app.name} (${manager})" ${cmd}`);
        }
    }

    if (!isWindows) {
        lines.push('');
        lines.push('echo "✔ $SUCCESS ok / ✖ $FAILED failed"');
    }

    return lines.join('\n');
}

// ─── Per-app script builder ───────────────────────────────────────────────────

/**
 * Builds individual scripts for each app.
 * Returns Record<appId, scriptContent>.
 * Skipped apps (no manager, no command for action) are OMITTED from the record.
 */
export function buildPerAppScripts(
    apps: CatalogApp[],
    action: ScriptAction,
    config: BuilderConfig,
): Record<string, string> {
    const result: Record<string, string> = {};
    const isWindows = config.platform === 'windows';
    const ext = isWindows ? 'ps1' : 'sh';

    for (const app of apps) {
        const manager = resolveManager(app, config);
        if (!manager) continue;

        const methods = getMethodsForPlatform(app, config)!;
        const method = findMethodByManager(methods, manager)!;
        const version = app.parameterized ? config.selectedVersions[app.id] : undefined;
        const cmd = getCommand(method, action, version);
        if (!cmd) continue;

        const filename = `${action}-${app.id}.${ext}`;
        const header = `# ===== ${filename} =====`;

        result[app.id] = isWindows ? [header, cmd].join('\n') : ['#!/usr/bin/env bash', header, cmd].join('\n');
    }

    return result;
}
